name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    workflow_dispatch:
    inputs:
      java-version:
        description: Java version
        default: "21"
jobs: 
  build: 
    uses: haidarim/ci-templates/.github/workflows/java-build-ci.yml@v1.0.4
    with:
      java-version: ${{ inputs.java-version }}

  test:
    needs: build
    uses: haidarim/ci-templates/.github/workflows/java-test-ci.yml@v1.1
    with:
      java-version: ${{ inputs.java-version }}
