name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env: 
  JAVA_VERSION: "21"
jobs: 
  build: 
    uses: haidarim/ci-templates/.github/workflows/java-build-ci.yml@v1.0.4
    with:
      java-version: ${{ env.JAVA_VERSION }}

  test:
    needs: build
    uses: haidarim/ci-templates/.github/workflows/java-test-ci.yml@v1.1
    with:
      java-version: ${{ env.JAVA_VERSION }}
